#!/bin/bash

FRAMEWORK_PATH="/projects/hira/Daniele/E15190-Unified-Analysis-Framework"

first_run=$2

if [ -z "$3" ]; then
  last_run=$2
else
  last_run=$3
fi

for run_num in `seq $first_run $last_run`
do
re='^[0-9]+$'

if ! [[ $run_num =~ $re ]] ; then
   echo "Error: Invalid run number" >&2; exit 1
fi

cat > submit.sh << EOF
#!/usr/bin/env bash
#--- sbatch option ---#
#SBATCH --time=100:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5000
#SBATCH --job-name=$run_num
#SBATCH --output=slurm/$run_num.out

module add intel

cd ${FRAMEWORK_PATH}
eval './$1 $run_num $run_num $4'
EOF

sbatch submit.sh
done

rm submit.sh
