2000 140 MeVA Ca40 on 124Sn, no Microball
2001 140 MeVA Ca40 on 124Sn, no Microball
2002 140 MeVA Ca40 on 124Sn, no Microball NW thr 2 MeV
2003 140 MeVA Ca40 on 124Sn, NW thr 2 MeV
2004 140 MeVA Ca40 on 124Sn, 
2005 140 MeVA Ca40 on 124Sn
2006 140 MeVA Ca40 on 124Sn
2007 140 MeVA Ca40 on 124Sn
2008 39 MeVA Ca40 on CH2n
2009 39 MeVA Ca40 on CH2n, Motherboard disc off?
2010 39 MeVA Ca40 on CH2n, Motherboard disc off?
2011 39 MeVA Ca40 on CH2n, Motherboard disc off?
2012 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2013 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2014 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2015 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2016 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2017 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2018 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2019 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2020 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2021 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2022 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2023 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2024 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2025 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2026 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2027 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2028 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2029 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2030 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2031 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2032 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2033 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2034 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2035 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2036 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2037 39 MeVA Ca40 on CH2n, CsI Gain increase 200 Motherboard disc off?
2038 neutron background test
2039 No pedestal suppression for HiRA Adc
2040 No pedestal suppression for HiRA Adc
2041 No pedestal suppression for HiRA Adc
2042 No pedestal suppression for HiRA Adc
2043 No pedestal suppression for HiRA Adc
2044 No pedestal suppression for HiRA Adc
2045 hot AmBe source, NW trigger only
2046 hot AmBe source, NW trigger only
2047 hot AmBe source, NW trigger only
2048 cosmics, NW trigger only
2049 cosmics, NW trigger only
2050 cosmics, NW trigger only
2051 cosmics, NW trigger only
2052 cosmics, NW trigger only
2053 cosmics, NW trigger only, no down scale
2054 cosmics, NW trigger only, no down scale
2055 cosmics, NW trigger only, no down scale
2056 First Run with New Beam
2057 First Run with New Beam
2058 First Run with New Beam
2059 First Run with New Beam
2060 First Run with New Beam
2061 First Run with New Beam
2062 First Run with New Beam
2063 First Run with New Beam
2064 First Run with New Beam
2065 First Run with New Beam
2066 Low emitance beam, 140 MeVA Ca40, blank target
2067 Low emitance beam, 140 MeVA Ca40, Sn124 target
2068 Low emitance beam, 140 MeVA Ca40, blank
2069 Low emitance beam, 140 MeVA Ca40, 124Sn target
2070 Low emitance beam, 140 MeVA Ca40, 124Sn target
2071 Low emitance beam, 140 MeVA Ca40, 124Sn target
2072 Low emitance beam, 140 MeVA Ca40, 124Sn target
2073 Neutron Wall Cosmics
2074 Sn124 Ca40 140MeV/u
2075 Sn124 Ca40 140MeV/u
2076 Sn124 Ca40 140MeV/u
2077 Sn124 Ca40 140MeV/u
2078 Sn124 Ca40 140MeV/u
2079 Sn124 Ca40 140MeV/u
2080 Sn124 Ca40 140MeV/u
2081 Sn124 Ca40 140MeV/u
2082 Sn124 Ca40 140MeV/u
2083 Sn124 Ca40 140MeV/u
2085 Sn124 Ca40 140MeV/u, DSS rotated out of the way
2086 Sn124 Ca40 140MeV/u
2087 Sn124 Ca40 140MeV/u after fixing hira trigger
2088 Sn124 Ca40 140MeV/u after fixing hira trigger
2090 Sn124 Ca40 140MeV/u after fixing hira trigger
2091 Sn124 Ca40 140MeV/u after fixing hira trigger
2092 Sn124 Ca40 140MeV/u after fixing hira trigger
2093 Sn124 Ca40 140MeV/u after fixing hira trigger
2094 Sn124 Ca40 140MeV/u, no CsI pedestal suppression
2095 Sn124 Ca40 140MeV/u, no CsI pedestal suppression
2096 Sn124 Ca40 140MeV/u, no CsI pedestal suppression
2097 Sn124 Ca40 140MeV/u, no CsI pedestal suppression
2098 Sn124 Ca40 140MeV/u, neutron uBall coincidence
2099 Sn124 Ca40 140MeV/u, neutron uBall coincidence
2100 Sn124 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2101 Sn124 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2102 Sn124 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2103 Sn124 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2104 Sn124 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2105 Sn124 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2106 Sn124 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2107 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2108 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2109 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2110 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2111 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2112 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2113 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2114 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2115 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2116 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2117 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2118 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2119 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2120 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2121 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2122 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2123 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2124 Hira Pulsers
2125 Back to data
2126 Back to data
2127 Back to data
2128 Back to data
2129 Back to data
2130 Changed CB for tele 5 EB
2131 Changed CB for tele 5 EB
2132 Changed CB for tele 5 EB
2133 Changed CB for tele 5 EB
2134 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences
2135 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences, replace 9 Chip
2136 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coincidences, replace 9 Chip
2137 Ni 58 Ca40 140MeV/u, hira singles low beam rate
2138 Ni 58 Ca40 140MeV/u, hira singles beam rate of 2137 x 10
2139 Ni 58 Ca40 140MeV/u, coincidence data and uball singles DS, changed EF3,4
2140 Ni 58 Ca40 140MeV/u, coincidence data and uball singles DS, CsI1 gain 170
2141 Ni 58 Ca40 140MeV/u, coincidence data and lots of changes see page 76
2142 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2143 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2144 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2145 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2146 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2147 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2148 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2149 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2150 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2151 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2152 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2153 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2154 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2155 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2156 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2157 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2158 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2159 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2160 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2161 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2162 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2163 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2164 Ni 58 Ca40 140MeV/u, coincidence data delayed triggers 150ns
2165 Ni 58 Ca40 140MeV/u, coincidence data
2166 Ni 58 Ca40 140MeV/u, coincidence data
2167 Ni 58 Ca40 140MeV/u, coincidence data
2168 Ni 58 Ca40 140MeV/u, coincidence data
2169 alpha source data, hira singles
2170 Ni 58 Ca40 140MeV/u, HiRA singles channel 0
2171 Ni 58 Ca40 140MeV/u, HiRA singles channel 1
2172 Ni 58 Ca40 140MeV/u, HiRA singles channel 2
2173 Ni 58 Ca40 140MeV/u, HiRA singles channel 3
2174 Ni 58 Ca40 140MeV/u, HiRA singles channel 4
2175 Ni 58 Ca40 140MeV/u, HiRA singles channel 5
2176 Ni 58 Ca40 140MeV/u, HiRA singles channel 6
2177 Ni 58 Ca40 140MeV/u, HiRA singles channel 6
2178 Ni 58 Ca40 140MeV/u, HiRA singles channel 8
2179 Ni 58 Ca40 140MeV/u, HiRA singles channel 9
2180 Ni 58 Ca40 140MeV/u, HiRA singles channel 10
2181 Ni 58 Ca40 140MeV/u, HiRA singles channel 11
2182 Ni 58 Ca40 140MeV/u, HiRA singles channel 12
2183 Ni 58 Ca40 140MeV/u, HiRA singles channel 13
2184 Ni 58 Ca40 140MeV/u, HiRA singles channel 14
2185 Ni 58 Ca40 140MeV/u, HiRA singles channel 15
2186 Ni 58 Ca40 140MeV/u, HiRA singles channel 16
2187 Ni 58 Ca40 140MeV/u, HiRA singles channel 17
2188 Ni 58 Ca40 140MeV/u, HiRA singles channel 18
2189 Ni 58 Ca40 140MeV/u, coincidence data 
2190 Ni 58 Ca40 140MeV/u, coincidence data 
2191 Ni 58 Ca40 140MeV/u, coincidence data 
2192 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2193 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2194 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2195 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2196 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2197 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2198 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2199 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2200 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2201 Ni 58 Ca40 140MeV/u, neutron uBall, hira uBall coin., new XLM
2202 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2203 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2204 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2205 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2206 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2207 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2208 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2209 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2210 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2211 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2212 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2213 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2214 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2215 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. reduced hira delay 1us
2216 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2217 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2218 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2219 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2220 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2221 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2222 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2223 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2224 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2225 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2226 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2227 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2228 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2229 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2230 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2231 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2232 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. hira trigger change
2233 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin. hira trigger change
2234 FA off
2235 FA10 (ch9) on 
2236 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2237 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2238 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2239 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2240 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2241 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2242 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2243 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2244 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2245 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2246 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2247 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2248 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin.
2249 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2250 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2251 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2252 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2253 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2254 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2255 Sn112 Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2256 Blank Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2257 Blank Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 2MeV
2258 Blank Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2259 112Sn Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2260 112Sn Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2261 112Sn Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2262 112Sn Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2263 112Sn Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2264 112Sn Ca40 140MeV/u, neutron uBall, hira uBall coin; NW thresholds 1MeV
2265 Ca40 140MeV/u,64Ni target neutron uBall, hira uBall coin NW thresholds 1MeV
2266 Ca40 140MeV/u,58Ni target neutron uBall, hira uBall coin NW thresholds 1MeV
2267 Ca40 140MeV/u,58Ni target neutron uBall, hira uBall coin NW thresholds 1MeV
2268 Ca40 140MeV/u,58Ni target neutron uBall, hira uBall coin NW thresholds 1MeV
2269 Ca40 140MeV/u,58Ni target neutron uBall, hira uBall coin NW thresholds 1MeV
2270 Ca40 140MeV/u,58Ni target neutron uBall, hira uBall coin NW thresholds 1MeV
2271 Ca40 140MeV/u,Blanktarget neutron uBall, hira uBall coin NW thresholds 1MeV
2272 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2273 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2274 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2275 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2276 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2277 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2278 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2279 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2280 Ca40 140MeV/u,Ni 58target neutron uBall, hira uBall coin NW thresholds 1MeV
2281 Ca40 56MeV/u, Sn112 neutron uBall, hira uBall coin NW thresholds 1MeV
2282 Ca40 56MeV/u, Sn112 neutron uBall, hira uBall coin NW thresholds 1MeV
2283 Ca40 56MeV/u, Sn112 neutron uBall, hira uBall coin NW thresholds 1MeV
2284 Ca40 56MeV/u, BLANK,  neutron uBall, hira uBall coin NW thresholds 1MeV
2285 Ca40 56MeV/u, BLANK,  neutron uBall, hira uBall coin NW thresholds 1MeV
2286 Ca40 56MeV/u, BLANK,  neutron uBall, hira uBall coin NW thresholds 1MeV
2287 Ca40 56MeV/u, 112Sn,  NO HIRA, NW thresholds 1MeV
2288 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2289 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2290 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2291 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2292 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2293 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2294 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2295 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2296 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2297 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2298 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2299 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2300 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2301 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2302 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2303 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2304 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2305 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2306 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2307 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2308 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2309 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2310 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2311 Ca40 56MeV/u, 112Sn,  NO HIRA Si, NW thresholds 1MeV
2312 Ca40 56MeV/u, CH2 target, HiRA singles, NW thresholds 1MeV
2313 Ca40 56MeV/u, blank target, HiRA singles, NW thresholds 1MeV
2314 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2315 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2316 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2317 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2318 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2319 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2320 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2321 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2322 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2323 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2324 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2325 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2326 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2327 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2328 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2329 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2330 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2331 Ca40 56MeV/u, 112Sn target, coinc trig, uBall DS 300, NW thresholds 1MeV
2332 Ca40 56MeV/u, blank, coinc trig, uBall DS 300, NW thresholds 1MeV
2333 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2334 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2335 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2336 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2337 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2338 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2339 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2340 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2341 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2342 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2343 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2344 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2345 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2346 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2347 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2348 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2349 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2350 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2351 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2352 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2353 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2354 Ca40 56MeV/u, Ni58, coinc trig, uBall DS 300, NW thresholds 1MeV
2355 Ca40 56MeV/u, Blank, coinc trig, uBall DS 300, NW thresholds 1MeV
2356 Ca40 56MeV/u, Blank, coinc trig, uBall DS 300, mult 1, NW thresholds 1MeV, 
2357 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, mult 1, NW thresholds 1MeV, 
2358 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2359 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2360 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2361 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2362 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2363 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2364 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2365 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2366 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2367 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2368 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2369 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2370 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2371 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2372 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2373 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2374 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2375 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2376 Ca40 56MeV/u, 112Sn, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2377 Ca40 56MeV/u, blank, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2378 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2379 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2380 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2381 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2382 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2383 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2384 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2385 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2386 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2387 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2388 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2389 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2390 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2391 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2392 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2393 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2394 Ca40 56MeV/u, 58Ni, coinc trig, uBall DS 300, NW thresholds 1MeV, 
2395 58Ni + scint MB = 3
2396 58Ni + scint, MB = 3, att 10k
2397 58Ni + scint, MB = 3, att .1M
2398 58Ni + scint, MB = 3, no beam
2399 blank + scint, MiniBall = 1, att .1M
2400 blank + scint, MiniBall = 1, no beam 
2401 blank + scint, MiniBall = 1, att .1M
2402 blank + scint, MiniBall = 1, att 10k
2403 blank + scint, MiniBall = 1, att 3k
2404 blank + scint, MiniBall = 3, no beam
2405 blank + scint, MiniBall = 3, att .1M
2406 blank + scint, MiniBall = 3, att 10k
2407 blank + scint, MiniBall = 3, att 3k
2408 blank, MiniBall = 3, no beam
2409 blank, MiniBall = 3, att .1M
2410 blank, MiniBall = 3, att 10k
2411 blank, MiniBall = 3, att 3k
2412 blank, MiniBall = 1, no beam
2413 blank, MiniBall = 1, att .1M
2414 blank, MiniBall = 1, att 10k
2415 blank, MiniBall = 1, att 3k
2416 112 Sn, MiniBall = 1, no beam
2417 112 Sn, MiniBall = 1, att .1M
2418 112 Sn, MiniBall = 1, att 10k
2419 112 Sn, MiniBall = 1, att 3k
2420 112 Sn, MiniBall = 3, no beam
2421 112 Sn, MiniBall = 3, no beam
2422 112 Sn, MiniBall = 3, att .1M
2423 112 Sn, MiniBall = 3, att 10k
2424 112 Sn, MiniBall = 3, att 3k
2425 112 Sn + scint, MiniBall = 3, no beam
2426 112 Sn + scint, MiniBall = 3, att .1M
2427 112 Sn + scint, MiniBall = 3, att 10k
2428 112 Sn + scint, MiniBall = 3, att 3k 
2429 112 Sn + scint, MicroBall = 1, no beam 
2430 112 Sn + scint, MicroBall = 1, att .1M 
2431 112 Sn + scint, MicroBall = 1, att 10K
2432 112 Sn + scint, MicroBall = 1, att 3K
2433 58 Ni + scint, MicroBall = 1, no beam
2434 58 Ni + scint, MicroBall = 1, att .1M
2435 58 Ni + scint, MicroBall = 1, att 10K
2436 58 Ni + scint, MicroBall = 1, att .1M
2437 58 Ni + scint, MicroBall = 1, att 10K
2438 58 Ni + scint, MicroBall = 1, att 3k
2439 58 Ni + scint, MicroBall = 3, no beam
2440 58 Ni + scint, MicroBall = 3, att .1M 
2441 58 Ni + scint, MicroBall = 3, att 10k
2442 58 Ni + scint, MicroBall = 3, att 3k
2443 58 Ni, MicroBall = 3, no beam 
2444 58 Ni, MicroBall = 3, .1M
2445 58 Ni, MicroBall = 3, att .1M
2446 58 Ni, MicroBall = 3, att 10k 
2447 58 Ni, MicroBall = 3, att 3k
2448 58 Ni, MicroBall = 3, att 10k redo
2449 58 Ni, MicroBall = 1,  no beam
2450 58 Ni, MicroBall = 1,  att .1M
2451 58 Ni, MicroBall = 1,  att 10k
2452 58 Ni, MicroBall = 1,  att 3k
2453 Blank, MicroBall = 1,  No beam 
2454 Blank, MicroBall = 3, att .1M
2455 Blank, MicroBall = 3, att 10k 
2456 Blank, MicroBall = 3, att 3k
2457 Blank, MicroBall = 3, att 3k
2458 Blank, MicroBall = 1, no beam
2459 Blank, MicroBall = 1, att .1M
2460 Blank, MicroBall = 1, att .1M
2461 Blank, MicroBall = 1, att 10k
2462 Blank, MicroBall = 1, att 3k
2463 Blank, MicroBall = 1, att .1M
2464 Blank + scint, MicroBall = 3, no beam 
2465 Blank + scint, MicroBall = 3, att .1M
2466 Blank + scint, MicroBall = 3, att .1M 
2467 Blank + scint, MicroBall = 3, att 10k 
2468 Blank + scint, MicroBall = 3, att 3k
2469 Blank + scint, MicroBall = 1, no beam
2470 Blank + scint, MicroBall = 1, att .1M
2471 Blank + scint, MicroBall = 1, att 10k
2472 Blank + scint, MicroBall = 1, att 3k
2473 Blank + scint, MicroBall = 1, att 3k
2474 124 Sn + scint, MicroBall = 1, no beam
2475 124 Sn + scint, MicroBall = 1, att .1M
2476 124 Sn + scint, MicroBall = 1, att 10k
2477 124 Sn + scint, MicroBall = 1, att 10k
2478 124 Sn + scint, MicroBall = 1, att 3k
2479 124 Sn + scint, MicroBall = 3, att 3k
2480 124 Sn + scint, MicroBall = 3, att 3k
2481 124 Sn + scint, MicroBall = 3, att 10k
2482 124 Sn + scint, MicroBall = 3, att 0.1M
2483 124 Sn + scint, MicroBall = 3, att 0.1M
2484 124 Sn + scint, MicroBall = 3, att 0.1M
2485 56 MeV 40Ca+58Ni, coin in, uball DS=300
2486 56 MeV 40Ca+58Ni, coin in, uball DS=300
2487 56 MeV 40Ca+58Ni, coin in, HiRA mball, NW mball, uball DS=300
2488 56 MeV 40Ca+58Ni, coin in, HiRA mball, NW mball, uball DS=300
2489 56 MeV 40Ca+58Ni, coin in, HiRA mball, NW mball, uball DS=300
2490 56 MeV, Blank, coin in, HiRA mball, NW mball, uball DS=300
2491 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2492 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2493 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2494 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2495 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2496 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2497 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2498 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2499 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2500 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2501 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2502 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2503 56 MeV, Ni58, coin in, HiRA mball, NW mball, uball DS=300
2504 56 MeV, Ni58, coin in, NO HiRA, NW mball, uball DS=300
2505 56 MeV, Ni58, coin in, NO HiRA, NW mball, uball DS=300
2506 56 MeV, Ni58, coin in, NO HiRA, NW mball, uball DS=300
2507 56 MeV, Ni58, coin in, NO HiRA, NW mball, uball DS=300
2508 56 MeV, Ni58, coin in, NO HiRA, NW mball, uball DS=300
2509 56 MeV, Ni58, coin in, NO HiRA, NW mball, uball DS=300
2510 56 MeV, Ni58, coin in, NO HiRA, NW mball, uball DS=300
2511 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2512 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2513 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2514 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2515 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2516 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2517 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2518 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2519 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2520 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2521 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2522 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2523 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300
2524 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300, FA all 900
2525 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300, FA all 950
2526 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300, FA all 850
2527 56 MeV, Ni64, coin in,HiRA mball, NW mball, uball DS=300, FA all 1000
2528 56 MeV, blank, coin in,HiRA mball, NW mball, uball DS=300
2529 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2530 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2531 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2532 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2533 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2534 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2535 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2536 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2537 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2538 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2539 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2540 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2541 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2542 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2543 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2544 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2545 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2546 56 MeV, Sn124, coin in,HiRA mball, NW mball, uball DS=300
2547 56 MeV, Ni64, norm, mult 3, att 10k 
2548 56 MeV, Ni64, norm, mult 3, att 30k 
2549 56 MeV, Ni64, norm, mult 3, att .1M
2550 56 MeV, Ni64, norm, mult 1, att .1M
2551 56 MeV, Ni64, norm, mult 1, att 30k
2552 56 MeV, Ni64, norm, mult 1, att 30k
2553 56 MeV, blank, norm, mult 1, att 10k
2554 56 MeV, 64Ni, norm, mult 1, att 10k no DSS
2555 56 MeV, 64Ni, norm, mult 1, att 30k no DSS
2556 56 MeV, 64Ni, norm, mult 1, att .1M no DSS
2557 56 MeV, 64Ni, norm, mult 3, att .1M no DSS
2558 56 MeV, 64Ni, norm, mult 3, att 30k no DSS
2559 56 MeV, 64Ni, norm, mult 3, att 10k no DSS
2560 CsI 1 pulser ramp 0.1 to 5V 31 steps
2561 CsI 2 pulser ramp 0.1 to 5V 31 steps
2562 CsI 2 pulser ramp 0.1 to 5V 31 steps
2563 CsI 3 pulser ramp 0.1 to 1.5V 11 steps
2564 CsI 3 pulser ramp 0.1 to 5V 31 steps
2565 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2566 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2567 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2568 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2569 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300, new FA settings
2570 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300, new FA settings
2571 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300, new FA settings
2572 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300, new FA settings
2573 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300, new FA settings
2574 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2575 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2576 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2577 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2578 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2579 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2580 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2581 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2582 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2583 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2584 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2585 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2586 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2587 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2588 Ni58, Ca40 at 140 MeVA, coin trig, uB DS 300
2589 blank, Ca40 at 140 MeVA, coin trig, uB DS 300
2590 blank, Ca40 at 140 MeVA, coin trig, uB DS 300
2591 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2592 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2593 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2594 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2595 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2596 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2597 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2598 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2599 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2600 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2601 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2602 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2603 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2604 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2605 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2606 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2607 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2608 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2609 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2610 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2611 58Ni, Ca40 at 140 MeVA, coin trig, uB DS 300
2612 Blank, Ca40 at 140 MeVA, coin trig, uB DS 300
2613 Blank, Ca40 at 140 MeVA, coin trig, uB DS 300
2614 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2615 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2616 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2617 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2618 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2619 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2620 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2621 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2622 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2623 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2624 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2625 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300
2626 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300, RF trig
2627 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300, RF trig
2628 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300, RF trig
2629 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300, RF trig
2630 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300, RF trig
2631 Sn112, Ca40 at 140 MeVA, coin trig, uB DS 300, RF trig
2632 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2633 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2634 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2635 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2636 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2637 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2638 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2639 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2640 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2641 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2642 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2643 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2644 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2645 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2646 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2647 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2648 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2649 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2650 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2651 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2652 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2653 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2654 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2655 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2656 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2657 Ni58, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2658 Blank, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2659 Blank, Ca40 at 140 MeVA, NWuB coinc, uB DS 300, RF trig
2662 Blank, DSS IN, uB Mult 3, Attn 3K
2663 Blank, DSS IN, uB Mult 1, Attn 3K
2664 124Sn, DSS IN, uB Mult 1, Attn 3K
2665 124Sn, DSS IN, uB Mult 1, Attn 10k
2666 124Sn, DSS IN, uB Mult 1, Attn .1M
2667 124Sn, DSS IN, uB Mult 3, Attn .1M
2668 124Sn, DSS IN, uB Mult 3, Attn 10k
2669 124Sn, DSS IN, uB Mult 3, Attn .1M
2670 64Ni, DSS IN, uB Mult 3, Attn 3k
2671 64Ni, DSS IN, uB Mult 3, Attn 10k
2672 64Ni, DSS IN, uB Mult 3, Attn .1M
2673 64Ni, DSS IN, uB Mult , Attn .1M
2674 64Ni, DSS IN, uB Mult , Attn 10k
2675 64Ni, DSS IN, uB Mult 1, Attn 3k
2676 112Sn, DSS IN, uB Mult 1, Attn 3k
2677 112Sn, DSS IN, uB Mult 1, Attn 10k
2678 112Sn, DSS IN, uB Mult 1, Attn .1M
2679 112Sn, DSS IN, uB Mult 3, Attn .1M
2680 112Sn, DSS IN, uB Mult 3, Attn 10k
2681 112Sn, DSS IN, uB Mult 3, Attn 10k
2682 112Sn, DSS IN, uB Mult 3, Attn 10k
2683 112Sn, DSS IN, uB Mult 3, Attn 3k
2684 112Sn, DSS IN, uB Mult 3, Attn 3k
2685 112Sn, DSS IN, uB Mult 3, Attn 10k
2686 58Ni, DSS IN, uB Mult 3, Attn 3k
2687 58Ni, DSS IN, uB Mult 3, Attn 10k
2688 58Ni, DSS IN, uB Mult 3, Attn .1M
2689 58Ni, DSS IN, uB Mult 1, Attn .1M
2690 58Ni, DSS IN, uB Mult 1, Attn 10k
2691 58Ni, DSS IN, uB Mult 1, Attn 3k
2692 58Ni, DSS OUT, uB Mult 1, Attn 3k
2693 58Ni, DSS OUT, uB Mult 1, Attn 10k
2694 58Ni, DSS OUT, uB Mult 1, Attn 0.1M
2695 58Ni, DSS OUT, uB Mult 3, Attn 0.1M
2696 58Ni, DSS OUT, uB Mult 3, Attn 10k
2697 58Ni, DSS OUT, uB Mult 3, Attn 3k
2698 58Ni, DSS OUT, uB Mult 3, Attn 3k, No beam
2699 124Sn, DSS OUT, uB Mult 1, Attn 3k
2700 124Sn, DSS OUT, uB Mult 1, Attn 10k
2701 124Sn, DSS OUT, uB Mult 1, Attn .1M
2702 124Sn, DSS OUT, uB Mult 3, Attn .1M
2703 124Sn, DSS OUT, uB Mult 3, Attn 10k
2704 124Sn, DSS OUT, uB Mult 3, Attn 3k
2705 124Sn, DSS OUT, uB Mult 3, Attn 3k, no beam
2706 blank, DSS OUT, uB Mult 3, Attn 3k
2707 blank, DSS OUT, uB Mult 1, Attn 3k
2708 blank, DSS OUT, uB Mult 1, no beam
2709 Ca40 at 140MeV, blank, coinc trigger, RF trigger
2710 124Sn at 140MeV, blank, coinc trigger, RF trigger
2711 124Sn at 140MeV, blank, coinc trigger, RF trigger
2712 124Sn at 140MeV, blank, coinc trigger, RF trigger
2713 124Sn at 140MeV, blank, coinc trigger, RF trigger
2714 124Sn at 140MeV, blank, coinc trigger, RF trigger
2715 124Sn at 140MeV, blank, coinc trigger, RF trigger
2716 124Sn at 140MeV, blank, coinc trigger, RF trigger
2717 124Sn at 140MeV, blank, coinc trigger, RF trigger
2718 124Sn at 140MeV, blank, coinc trigger, RF trigger
2719 124Sn at 140MeV, blank, coinc trigger, RF trigger
2720 124Sn at 140MeV, blank, coinc trigger, RF trigger
2721 124Sn at 140MeV, blank, coinc trigger, RF trigger
2722 140MeV, blank, coinc trigger, RF trigger, ShadowB in
2723 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2724 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2725 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2726 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2727 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2728 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2729 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2730 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2731 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2732 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2733 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2734 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2735 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2736 140MeV, 64Ni, coinc trigger, RF trigger, ShadowB in
2737 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2738 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2739 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2740 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2741 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2742 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2743 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2744 140MeV, 64Ni, uball NW, NO HiRA, RF trigger, ShadowB in
2745 140MeV, blank, uball NW, NO HiRA, RF trigger, ShadowB in
2746 No beam, blank, uball NW, NO HiRA, RF trigger, ShadowB in
2747 140MeV Ramp: 30k, uBall3, DSS in
2748 140MeV Ramp: 30k, uBall 1, DSS in
2749 140MeV Ramp: 30k, uBall 1, DSS in ~TARGET CHANGE NO BEAM~
2750 140MeV Ramp: 30k, uBall 1, DSS in ~TARGET CHANGE NO BEAM, NO RF~
2751 140MeV Ramp: 30k, uBall 1, DSS in ~TARGET CHANGE NO BEAM, NO PULSER~
2752 140MeV Ramp: 30k, uBall 1, DSS in ~TARGET CHANGE~
2753 140MeV Ramp: 0.1M, uBall 1, DSS in ~TARGET CHANGE~
2754 140MeV Ramp: 1M, uBall 1, DSS in
2755 140MeV Ramp: 0.1M, uBall 1, DSS in
2756 140MeV Ramp: 30K, uBall 1, DSS in
2757 140MeV Ramp: 10K, uBall 1, DSS in
2758 140MeV Ramp: 0.1M, uBall 1, DSS in
2759 140MeV Ramp: 1M, uBall 1, DSS in
2760 140MeV Ramp: 1M, uBall 1, DSS in
2761 140MeV Ramp: 1M, uBall 1, DSS in
2763 140MeV Ramp: 112Sn, 10K, uBall 3, DSS in
2764 140MeV Ramp: 112Sn, 0.1M, uBall 3, DSS in
2765 140MeV Ramp: 112Sn, 0.1M, uBall 3, DSS in
2766 140MeV Ramp: 112Sn, 1M, uBall 3, DSS in
2767 140MeV Ramp: 112Sn, 10K, uBall 3, DSS in
2768 140MeV Ramp: 112Sn, NO BEAM, uBall 3, DSS in
2769 140MeV Ramp: 58Ni, 10K, uBall 3, DSS in
2770 140MeV Ramp: 58Ni, 0.1M, uBall 3, DSS in
2772 140MeV Ramp: 58Ni, 1M, uBall 3, DSS in
2773 140MeV Ramp: 58Ni, 1M, uBall 1, DSS in
2774 140MeV Ramp: 58Ni, 0.1M, uBall 1, DSS in
2775 140MeV Ramp: 58Ni, 10K, uBall 1, DSS in
2776 140MeV Ramp: 58Ni, NO BEAM, uBall 1, DSS in
2777 140MeV Ramp: 64Ni, 10K, uBall 1, DSS in
2778 140MeV Ramp: 64Ni, 0.1M, uBall 1, DSS in
2779 140MeV Ramp: 64Ni, 1M, uBall 1, DSS in
2780 140MeV Ramp: 64Ni, 10K, uBall 3, DSS in
2781 140MeV Ramp: 64Ni, 0.1M, uBall 3, DSS in
2782 140MeV Ramp: 64Ni, 1M, uBall 3, DSS in
2783 140MeV Ramp: No Beam, 1M, uBall 3, DSS in
2784 140MeV Ramp: 124Sn, 10k, uBall 3, DSS in
2785 140MeV Ramp: 124Sn, 0.1M, uBall 3, DSS in
2786 140MeV Ramp: 124Sn, 1M, uBall 3, DSS in
2787 140MeV Ramp: 124Sn, 10k, uBall 1, DSS in
2788 140MeV Ramp: 124Sn, 0.1M, uBall 1, DSS in
2789 140MeV Ramp: 124Sn, 1M, uBall 1, DSS in
2790 140MeV Ramp: No beam, 1M, uBall 1, DSS in
2791 140MeV Ramp: 124Sn, 10K, uBall 1, DSS in
2792 140MeV Ramp: blank, 0.1M, uBall 1, DSS in
2793 140MeV Ramp: blank, 10K, uBall 3, DSS in
2794 140MeV Ramp: blank, uBall 3, DSS in/out no beam
2795 140MeV Ramp: 124Sn, uBall 3, DSS in/out no beam
2796 140MeV Ramp: 124Sn, uBall 3, DSS out 
2797 140MeV Ramp: 124Sn, uBall 3, att 1M,  DSS out 
2798 140MeV Ramp: 124Sn, uBall 1, att 10k,  DSS out 
2799 140MeV Ramp: 124Sn, uBall 1, att 0.1M,  DSS out 
2800 140MeV Ramp: 124Sn, uBall 1, att 1M,  DSS out 
2801 140MeV Ramp: no beam, uBall 1, att 1M,  DSS out 
2802 140MeV Ramp: 64Ni, uBall 1, att 10K,  DSS out 
2803 140MeV Ramp: 64Ni, uBall 1, att 0.1M,  DSS out 
2804 140MeV Ramp: 64Ni, uBall 1, att 1M,  DSS out 
2805 140MeV Ramp: 64Ni, uBall 3, att 10K,  DSS out 
2806 140MeV Ramp: 64Ni, uBall 3, att 0.1M,  DSS out 
2807 140MeV Ramp: 64Ni, uBall 3, att 1M,  DSS out 
2808 140MeV Ramp: no beam, uBall 3, att 1M,  DSS out 
2809 140MeV Ramp: 58Ni, uBall 3, att 10K,  DSS out 
2810 140MeV Ramp: 58Ni, uBall 3, att 0.1M,  DSS out 
2811 140MeV Ramp: 58Ni, uBall 3, att 1M,  DSS out 
2812 140MeV Ramp: 58Ni, uBall 1, att 10K,  DSS out 
2813 140MeV Ramp: 58Ni, uBall 1, att 0.1M,  DSS out 
2814 140MeV Ramp: 58Ni, uBall 1, att 1M,  DSS out 
2815 140MeV Ramp: No beam, uBall 1, att 10K,  DSS out 
2816 140MeV Ramp: mult 1, uBall 1, att 10K,  DSS out 
2817 140MeV Ramp: mult 1, uBall 1, att 10K,  DSS out 
2818 140MeV Ramp: mult 1, uBall 1, att 0.1M,  DSS out 
2819 140MeV Ramp: mult 1, uBall 1, att 1M,  DSS out 
2820  Ramp: mult 1, uBall 1, att 1M,  DSS out , no beam
2821 Ca140MeV/u Ramp: uball mult 3, att 10k,  DSS out 
2822 Ca140MeV/u Ramp: uball mult 3, att .1M,  DSS out 
2823 Ca140MeV/u Ramp: uball mult 3, att 1M,  DSS out 
2824 Ca140MeV/u Ramp: no beam, uball mult 3, att 1M,  DSS out 
2825 40Ca at 140MeV/u; CH2, HiRA singles
2826 40Ca at 140MeV/u; CH2, HiRA singles
2827 40Ca at 140MeV/u; CH2, HiRA singles
2828 40Ca at 140MeV/u; CH2, HiRA singles
2829 40Ca at 140MeV/u; CH2, HiRA singles
2830 40Ca at 140MeV/u; 112Sn, Coin Trig,
2831 40Ca at 140MeV/u; 112Sn, Coin Trig,
2832 40Ca at 140MeV/u; 112Sn, Coin Trig,
2833 40Ca at 140MeV/u; 112Sn, Coin Trig,
2834 40Ca at 140MeV/u; 112Sn, Coin Trig,
2835 40Ca at 140MeV/u; 112Sn, Coin Trig,
2836 40Ca at 140MeV/u; 112Sn, Coin Trig,
2837 40Ca at 140MeV/u; 112Sn, Coin Trig,
2838 40Ca at 140MeV/u; 112Sn, Coin Trig,
2839 40Ca at 140MeV/u; 112Sn, Coin Trig,
2840 40Ca at 140MeV/u; 112Sn, Coin Trig,
2841 40Ca at 140MeV/u; 112Sn, Coin Trig,
2842 40Ca at 140MeV/u; 112Sn, Coin Trig,
2843 40Ca at 140MeV/u; 112Sn, Coin Trig,
2844 40Ca at 140MeV/u; 112Sn, Coin Trig,
2845 40Ca at 140MeV/u; 112Sn, Coin Trig,
2846 40Ca at 140MeV/u; 112Sn, Coin Trig,
2847 40Ca at 140MeV/u; blank, Coin Trig,
2848 40Ca at 140MeV/u; 58Ni, Coin Trig,
2849 40Ca at 140MeV/u; 58Ni, Coin Trig,
2850 40Ca at 140MeV/u; 58Ni, Coin Trig,
2851 40Ca at 140MeV/u; 58Ni, Coin Trig,
2852 40Ca at 140MeV/u; 58Ni, Coin Trig,
2853 40Ca at 140MeV/u; 58Ni, Coin Trig,
2854 40Ca at 140MeV/u; 58Ni, Coin Trig,
2855 40Ca at 140MeV/u; 58Ni, Coin Trig,
2856 40Ca at 140MeV/u; 58Ni, Coin Trig,
2857 40Ca at 140MeV/u; 58Ni, Coin Trig,
2858 40Ca at 140MeV/u; 58Ni, Coin Trig,
2859 40Ca at 140MeV/u; 58Ni, Coin Trig,
2860 40Ca at 140MeV/u; 58Ni, Coin Trig,
2861 40Ca at 140MeV/u; 58Ni, Coin Trig,
2862 40Ca at 140MeV/u; 58Ni, Coin Trig,
2863 40Ca at 140MeV/u; 58Ni, Coin Trig,
2864 40Ca at 140MeV/u; 58Ni, Coin Trig,
2865 40Ca at 140MeV/u; 58Ni, Coin Trig,
2866 40Ca at 140MeV/u; 58Ni, Coin Trig,
2867 40Ca at 140MeV/u; 58Ni, Coin Trig,
2868 40Ca at 140MeV/u; 58Ni, Coin Trig,
2869 40Ca at 140MeV/u; 58Ni, Coin Trig,
2870 40Ca at 140MeV/u; 58Ni, Coin Trig,
2871 Alpha source with SnPb foils
2872 Alpha source with SnPb foils
2873 Alpha source with SnPb foils
2874 Si Calibration,Fine, Back, 21 steps, 5 sec, 0.001V-0.181V, CB 1,3,5,7
2875 Si Calibration,Fine, Back, 21 steps, 5 sec, 0.001V-0.181V, CB 9,11,1*,3*
2876 Si Calibration,Fine, Back, 21 steps, 5 sec, 0.001V-0.181V, CB 5*,7*,9*,11*
2877 Si Calibration,Fine, Fronts, 21 steps, 5 sec, 0.001V-0.181V, CB 2,4,6,8
2878 Si Calibration,Fine, Fronts, 21 steps, 5 sec, 0.001V-0.181V, CB 10,12,2*,4*
2879 Si Calibration,Fine, Fronts, 21 steps, 5sec, 0.001V-0.181V,CB 6*,8*,10*,12*
2880 Si Cal, Low, Fronts, 21 steps, 5sec, 0.15V-0.49V,CB 2,4,6,8
2881 Si Cal, Low, Fronts, 21 steps, 5sec, 0.15V-0.49V,CB 10,12,2*,4*
2882 Si Cal, Low, Fronts, 21 steps, 5sec, 0.15V-0.49V,CB 6*,8*,10*,12*
2883 Si Cal, Low, Backs, 21 steps, 5sec, 0.15V-0.49V,CB 1,3,5,7
2884 Si Cal, Low, Backs, 21 steps, 5sec, 0.15V-0.49V,CB 9,11,1*,3*
2885 Si Cal, Low, Backs, 21 steps, 5sec, 0.15V-0.49V,CB 5*,7*,9*,11*
2886 Si Cal, High, Backs, 21 steps, 5sec, 0.49V-3.49V,CB 1,3,5,7
2887 Si Cal, High, Backs, 31 steps, 5sec, 0.49V-4.99V,CB 1,3,5,7
2888 Si Cal, High, Backs, 31 steps, 5sec, 0.49V-4.99V,CB 9,11,1*,3*
2889 Si Cal, High, Backs, 31 steps, 5sec, 0.49V-4.99V,CB 5*,7*,9*,11*
2890 Si Cal, High, Fronts, 31 steps, 5sec, 0.49V-4.99V,CB 2,4,6,8
2891 Si Cal, High, Fronts, 31 steps, 5sec, 0.49V-4.99V,CB 10,12,2*,4*
2892 Si Cal, High, Fronts, 31 steps, 5sec, 0.49V-4.99V,CB 6*,8*,10*,12*
2893 CsI Sh0 Pulser Cal Course, 170 Gain, 0.1V-5V, 31 steps, 5 sec
2894 CsI Sh0 Pulser Cal Course, 170 Gain, 0.1V-5V, 31 steps, 5 sec
2895 CsI Sh0 Pulser Cal Course, 130 Gain, 0.1V-5V, 31 steps, 5 sec
2896 CsI Sh0 Pulser Cal Course, 200 Gain, 0.1V-5V, 31 steps, 5 sec
2897 CsI Sh1 Pulser Cal Course, 130 Gain, 0.1V-1.5V, 11 steps, 5 sec
2898 CsI Sh1 Pulser Cal Course, 200 Gain, 0.1V-1.5V, 11 steps, 5 sec
2899 CsI Sh2 Pulser Cal Course, 130 Gain, 0.1V-1.5V, 11 steps, 5 sec
2900 CsI Sh2 Pulser Cal Course, 200 Gain, 0.1V-1.5V, 11 steps, 5 sec
2901 CsI Sh2 Pulser Cal Fine, 130 Gain, 0.001V-0.3V, 21 steps, 5 sec
2902 CsI Sh2 Pulser Cal Fine, 200 Gain, 0.001V-0.3V, 21 steps, 5 sec
2903 CsI Sh1 Pulser Cal Fine, 200 Gain, 0.001V-0.3V, 21 steps, 5 sec
2904 CsI Sh1 Pulser Cal Fine, 130 Gain, 0.001V-0.3V, 21 steps, 5 sec
2905 CsI Sh0 Pulser Cal Fine, 130 Gain, 0.001V-0.3V, 21 steps, 5 sec
2906 CsI Sh0 Pulser Cal Fine, 170 Gain, 0.001V-0.3V, 21 steps, 5 sec
2907 CsI Sh0 Pulser Cal Fine, 200 Gain, 0.001V-0.3V, 21 steps, 5 sec
2908 CsI Sh0 Pulser Cal Course 200 Gain, 0.1V-5V, 31 steps, 5 sec
2909 CsI Sh0 Pulser Cal Course 170 Gain, 0.1V-5V, 31 steps, 5 sec
2910 CsI Sh0 Pulser Cal Course 130 Gain, 0.1V-5V, 31 steps, 5 sec
2911 CsI Sh1 Pulser Cal Course 130 Gain, 0.1V-1.5V, 11 steps, 5 sec,csi trig
2912 CsI Sh1 Pulser Cal Course 200 Gain, 0.1V-1.5V, 11 steps, 5 sec,csi trig
2913 CsI Sh2 Pulser Cal Course 130 Gain, 0.1V-1.5V, 11 steps, 5 sec,csi trig
2914 CsI Sh2 Pulser Cal Course 200 Gain, 0.1V-1.5V, 11 steps, 5 sec,csi trig
2915 Si Alpha Cal,No SnPb foil
2916 Si Alpha Cal,No SnPb foil
2917 VW Co60 B18 bottom
2918 VW Co60 B14 bottom
2919 VW Co60 B16 bottom
2920 VW cosmics
2921 VW Bar 01 bottom
2922 VW Bar 05 bottom
2923 VW Bar 06 bottom
2924 VW Bar 02 bottom
2925 VW Bar 09 bottom
2926 VW Bar 13 bottom
2927 VW Bar 15 bottom
2928 VW Bar 03 bottom
2929 VW Bar 07 bottom
2930 VW Bar 11 bottom
2931 VW Bar 23 bottom
2932 VW Bar 19 bottom
2933 VW Bar 21 bottom
2934 VW Bar 22 bottom
2935 VW Bar 24 bottom
2936 VW Bar 08 bottom
2937 VW Bar 12 bottom
2938 VW Bar 20 bottom
2939 VW Bar 17 bottom
2940 VW Bar 04 bottom
2941 VW Bar 10 bottom
2942 VW P02 bottom
2943 VW Bar 18 top
2944 VW Bar 14 top
2945 VW Bar 16 top
2946 VW Bar 01 top
2947 VW Bar 05 top
2948 VW Bar 06 top
2949 VW Bar 02top
2950 VW Bar 09 top
2951 VW Bar 13 top
2952 VW Bar 15 top
2953 VW Bar 03 top
2954 VW Bar 07 top
2955 VW Bar 11 top
2956 VW Bar 23 top (20cm)
2957 VW B19 top (20cm)
2958 VW B21 top (20cm)
2959 VW B22 top (20cm)
2960 VW B24 top (20cm)
2961 VW B08 top (20cm)
2962 VW B12 top (20cm)
2963 VW B20 top (20cm)
2964 VW B17 top (20cm)
2965 VW B04 top (20cm)
2966 VW B10 top (20cm)
2967 VW P02 top (20cm)
2968 VW B18 top (20cm)
2969 VW B14 top (20cm)
2970 VW B16 top (20cm)
2971 VW B01 top (20cm)
2972 VW B05 top (20cm)
2973 VW B06 top (20cm)
2974 VW B02 top (20cm)
2975 VW B09 top (20cm)
2976 VW B13 top (20cm)
2977 VW B15 top (20cm)
2978 VW B03 top (20cm)
2979 VW B07 top (20cm)
2980 VW B20 top (20cm)
2981 VW B20 botom, old HV (T924V, B 952V)
2982 VW B20 botom, old HV (T924V, B 952V) other discs off
2983 VW B20 botom, old HV (T924V, B 952V) other discs off, Th 1
2984 VW B20 top (20cm), old HV (T924V, B 952V) other discs off, Th 1
2985 VW B20 top (20cm), old HV (T924V, B 952V) other discs off
2986 VW pedestal
2987 VW pedestal
2989 NW cosmic ray Co60HV threshold:1MeV
2990 CsI Pulser Cal, 1micro rise, Course, Sh0, 0.1V-5V, 31 steps 5s, 130 gain
2991 CsI Pulser Cal, 1micro rise, Course, Sh0, 0.1V-5V, 31 steps 5s, 170 gain
2992 CsI Pulser Cal, 1micro rise, Course, Sh0, 0.1V-5V, 31 steps 5s, 200 gain
2993 CsI Pulser Cal, 1micro rise, Course, Sh1, 0.1V-1.5, 11 steps 5s, 130 gain
2994 CsI Pulser Cal, 1micro rise, Course, Sh1, 0.1V-1.5, 11 steps 5s, 130 gain
2995 CsI Pulser Cal, 1micro rise, Course, Sh1, 0.1V-1.5, 11 steps 5s, 130 gain
2996 CsI Pulser Cal, 1micro rise, Course, Sh1, 0.1V-1.5, 11 steps 5s, 130 gain
2997 CsI Pulser Cal, 1micro rise, Course, Sh1, 0.1V-1.5, 11 steps 5s, 200 gain
2998 CsI Pulser Cal, 1micro rise, Course, Sh2, 0.1V-1.5, 11 steps 5s, 130 gain
2999 CsI Pulser Cal, 1micro rise, Course, Sh2, 0.1V-1.5, 11 steps 5s, 200 gain
3000 CsI Pulser Cal, 1micro rise, fine, Sh2, 0.001V-0.2, 21 steps 5s, 200 gain
3001 CsI Pulser Cal, 1micro rise, fine, Sh2, 0.001V-0.2, 21 steps 5s, 130 gain
3002 CsI Pulser Cal, 1micro rise, fine, Sh1, 0.001V-0.2, 21 steps 5s, 200 gain
3003 CsI Pulser Cal, 1micro rise, fine, Sh1, 0.001V-0.2, 21 steps 5s, 130 gain
3004 CsI Pulser Cal, 1micro rise, fine, Sh0, 0.001V-0.2, 21 steps 5s, 200 gain
3005 CsI Pulser Cal, 1micro rise, fine, Sh0, 0.001V-0.2, 21 steps 5s, 170 gain
3006 CsI Pulser Cal, 1micro rise, fine, Sh0, 0.001V-0.2, 21 steps 5s, 130 gain
3007 CsI Pulser Cal, 10micro rise, course Sh0, 0.1V-5, 31 steps 5s, 130 gain
3008 CsI Pulser Cal, 10micro rise, course Sh0, 0.1V-5, 31 steps 5s, 170 gain
3009 CsI Pulser Cal, 10micro rise, course Sh0, 0.1V-5, 31 steps 5s, 200 gain
3010 CsI Pulser Cal, 10micro rise, course Sh1, 0.1V-5, 31 steps 5s, 130 gain
3011 CsI Pulser Cal, 10micro rise, course Sh1, 0.1V-5, 31 steps 5s, 200 gain
3012 CsI Pulser Cal, 10micro rise, course Sh2, 0.1V-5, 31 steps 5s, 130 gain
3013 CsI Pulser Cal, 10micro rise, course Sh2, 0.1V-5, 31 steps 5s, 200 gain
3014 NW cosmic rays Co60HV threshold:1MeV
3015 junk test of multilogger
3016 junk test of multilogger
3017 junk test of multilogger
3018 VW bar 20 bottom Co source 20 cm(test)
3019 VW bar 20 bottom Co source 20 cm(test)
3020 VW bar 20 bottom Co source 20 cm(test)
3021 VW B20 bottom Co source 20cm
3022 VW B20 bottom Cs source 20cm
3023 VW B20 bottom Cs source 20cm with pedestal
3024 VW B20 bottom Cs source 20cm with pedestal
3025 VW B20 bottom Cs source 20cm with pedestal
3026 VW B20 top Cs source 20cm with pedestal
3027 VW B20 top Co source 20cm with pedestal
3028 junk test
3029 VW B20 bottom Co source 20cm with pedestal
3030 VW B20 top Co source 20cm with pedestal
3031 VW B20 top Co source 20cm with pedestal (connected to 2 QDCs)
3032 VW B20 bottom Co source 20cm with pedestal (connected to 2 QDCs)
3033 VW B20 bottom Co 20cm with pedestal (connected to 2 QDCs)(bottom wrapped)
3034 VW B20 top Co 20cm with pedestal (connected to 2 QDCs)(bottom wrapped)
3035 VW B20 top Co/20cm/pedestal/connected to 2 QDCs/bottom wrapped/HV reduced
3036 VW B20 top Co/20cm/pedestal/connected to 2 QDCs/bottom wrapped/HV reduced
3037 VW B20 top Co/20cm/pedestal/connected to 2 QDCs/bottom wrapped/HV reduced
3039 VW B01 bottom Co/20cm/
3040 VW B01 top Co/20cm/
3041 VW B01 top Co/20cm
3042 VW B01 bottom Co/20cm
3043 VW B03 bottom Co/20cm
3044 VW B03 top Co/20cm
3045 VW B03 top Co/20cm
3046 VW B03 bottom Co/20cm
3047 VW B23 bottom Co/20cm
3048 VW B23 bottom Co/20cm
3049 VW B23 bottom Co/20cm
3050 VW B23 top Co/20cm/th 2
3051 VW B23 top Co/20cm/th 3
3052 VW B23 top Co/20cm/th 4
3053 VW B20 bottom Co/20cm/ th 4
3054 VW B20 bottom Co/20cm/ th 2
3055 VW B20 top Co/20cm/ th 2
3056 VW B17 wired as B20 top Co/20cm/ th 2
3057 VW B17 wired as B20 bottom Co/20cm/ th 2
3058 VW B17 wired as B20 bottom Co/20cm/ th 2 
3059 VW B17 wired as B20 top Co/20cm/ th 2 
3060 VW B20 wired as B17 top Co/20cm/ th 2 
3061 VW B20 wired as B17 bottom Co/20cm/ th 2 
3062 VW B20  HV reduced by 50V bottom Co/20cm/ th 2 
3063 VW B20  HV reduced by 50V bottom Co/60cm/ th 2 
3064 VW B20  HV reduced by 50V center Co/0cm/ th 2 
3065 VW B20  HV reduced by 50V top Co/60cm/ th 2 
3066 VW B20  HV reduced by 50V top Co/20cm/ th 2 
3067 VW B20  HV reduced by 50V top Co/20cm/ th 2 
3068 VW B20  HV reduced by 100V top Co/60cm/ th 2 
3069 VW B20  HV reduced by 100V center Co/0cm/ th 2 
3070 VW B20  HV reduced by 100V bottom Co/60cm/ th 2 
3071 VW B20  HV reduced by 100V bottom Co/20cm/ th 2 
3072 AmBe source data, gain = Co60 Thresh = 1MeV
3073 AmBe source data, gain = Co60 Thresh = 1MeV
3074 AmBe source data, gain = Co60 Thresh = 1MeV higher position: around bar #9
3075 Junk test of new stagearea
3076 alpha run SnPb foils on
4000 Ca48 140MeVA, CH2 target, HiRA Singles
4001 Ca48 140MeVA, CH2 target, HiRA Singles
4002 Ca48 140MeVA, CH2 target, HiRA Singles, Pedistal Off
4003 Ca48 140MeVA, CH2 target, HiRA Singles, Pedistal Off
4004 Ca48 140MeVA, CH2 target, HiRA Singles
4005 Ca48 140MeVA, CH2 target, HiRA Singles
4006 Ca48 140MeVA, Sn124, Coincidence Trigger 
4007 Ca48 140MeVA, Sn124, Coincidence Trigger 
4008 Ca48 140MeVA, Sn124, Coincidence Trigger 
4009 Ca48 140MeVA, Sn124, Coincidence Trigger 
4010 Ca48 140MeVA, Sn124, Coincidence Trigger 
4011 Ca48 140MeVA, Sn124, Coincidence Trigger 
4012 Ca48 140MeVA, Sn124, Coincidence Trigger 
4013 Ca48 140MeVA, Sn124, Coincidence Trigger 
4014 NW pedestal run, bypass Korean Fast amps
4015 Ca48 140MeVA, Sn124, Coincidence Trigger
4016 Ca48 140MeVA, Sn124, Coincidence Trigger
4017 No beam NW cosmic, DS
4018 Ca48 140MeV Sn124 Coincidence NW debugging
4019 Ca48 140MeV Sn124 Coincidence NW debugging
4020 Ca48 140MeV Sn124 Coincidence NW debugging, no threshold
4021 Ca48 140MeV CH2 Coincidence, HiRA singles
4022 Ca48 140MeV CH2 Coincidence, HiRA singles
4023 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4024 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4025 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4026 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4027 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4028 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4029 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4030 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4031 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4032 Ca48 140MeV 64Ni Coincidence, Hira+MBall
4033 Ca48 140MeV Blank Coincidence, Hira+MBall
4034 Ca48 28MeV CH2 coincidence MBall single:301, HiRA single, NW single: 32
4035 Ca48 28MeV CH2 coincidence MBall single:301, HiRA single, NW single: 32
4036 Ca48 28MeV CH2 coincidence MBall single:301, HiRA single, NW single: 32
4037 Ca48 28MeV CH2 coincidence MBall single:301, HiRA single, NW single: 32
4038 Cosmics coincidence MBall single:301, HiRA single, NW single: 32
4039 56MeV CH2, coincidence MBall single:301, HiRA single, NW single: 32
4040 56MeV CH2, coincidence MBall single:301, HiRA single, NW single: 32
4041 140MeV Blanck, coincidence trigger and RF trigger
4042 140MeV 124Sn, coincidence trigger and RF trigger
4043 140MeV 124Sn, coincidence trigger and RF trigger
4044 140MeV 124Sn, coincidence trigger and RF trigger
4045 140MeV 124Sn, coincidence trigger and RF trigger
4046 140MeV 124Sn, coincidence trigger and RF trigger
4047 140MeV 124Sn, coincidence trigger and RF trigger
4048 140MeV 124Sn, coincidence trigger and RF trigger
4049 140MeV 124Sn, coincidence trigger and RF trigger
4050 140MeV 124Sn, coincidence trigger and RF trigger
4051 140MeV 124Sn, coincidence trigger and RF trigger
4052 140MeV 124Sn, coincidence trigger and RF trigger
4053 140MeV 124Sn, coincidence trigger and RF trigger
4054 140MeV 124Sn, coincidence trigger and RF trigger
4055 140MeV 124Sn, coincidence trigger and RF trigger
4056 140MeV 124Sn, coincidence trigger and RF trigger
4057 140MeV 124Sn, coincidence trigger and RF trigger
4058 140MeV 124Sn, coincidence trigger and RF trigger
4059 140MeV 124Sn, coincidence trigger and RF trigger
4060 140MeV 124Sn, coincidence trigger and RF trigger
4061 140MeV 124Sn, coincidence trigger and RF trigger
4062 140MeV 124Sn, coincidence trigger and RF trigger
4063 140MeV 124Sn, coincidence trigger and RF trigger
4064 140MeV 124Sn, coincidence trigger and RF trigger
4065 140MeV 124Sn, coincidence trigger and RF trigger
4066 140MeV 124Sn, coincidence trigger and RF trigger
4067 140MeV 124Sn, coincidence trigger and RF trigger
4068 140MeV 124Sn, coincidence trigger and RF trigger
4069 140MeV 124Sn, coincidence trigger and RF trigger, TDC depth 4
4070 140MeV 124Sn, coincidence trigger and RF trigger, TDC depth 4, wider window
4071 140MeV 124Sn, coincidence trigger and RF trigger, TDC depth 4, diff offset
4072 140MeV 124Sn, uball-NW coincidence trigger and RF trigger
4073 140MeV 124Sn, uball-NW coincidence trigger, NO RF trig
4074 140MeV 124Sn, coincidence trigger, uB DS, RF trig
4075 140MeV 124Sn, coincidence trigger, uB DS, RF trig
4076 140MeV 124Sn, coincidence trigger, uB DS, RF trig
4077 140MeV 124Sn, coincidence trigger, uB DS, RF trig
4078 140MeV 124Sn, coincidence trigger, uB DS, RF trig
4079 140MeV blank, coincidence trigger, uB DS, RF trig
4080 No Beam blank, coincidence trigger, uB DS, RF trig
4081 140MeV blank, coincidence trigger, uB DS, RF trig
4082 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4083 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4084 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4085 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4086 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4087 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4088 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4089 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4090 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4091 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4092 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4093 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4094 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4095 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4096 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4097 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4098 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4099 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4100 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4101 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4102 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4103 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4104 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4105 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4106 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4107 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4108 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4109 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4110 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4111 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4112 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4113 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4114 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4115 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4116 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4117 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4118 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4119 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4120 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4121 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4122 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4123 140MeV 64Ni, coincidence trigger, uB DS, RF trig
4124 140MeV blank, coincidence trigger, uB DS, RF trig
4125 140MeV 112Sn, coincidence trigger, uB DS, RF trig
4126 140MeV 112Sn, coincidence trigger, uB DS, RF trig
4127 140MeV 112Sn, coincidence trigger, uB DS, RF trig
4128 140MeV 112Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4129 140MeV 112Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4130 140MeV 112Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4131 140MeV 112Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4132 140MeV 112Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4133 140MeV blank, coincidence trigger(no NW+uB), uB DS, RF trig
4134 140MeV blank, coincidence trigger(no NW+uB), uB DS, RF trig
4135 140MeV 58Ni, coincidence trigger(no NW+uB), uB DS, RF trig
4136 140MeV 58Ni, coincidence trigger(no NW+uB), uB DS, RF trig
4137 140MeV 58Ni, coincidence trigger(no NW+uB), uB DS, RF trig
4138 140MeV 58Ni, coincidence trigger(no NW+uB), uB DS, RF trig
4139 140MeV 58Ni, coincidence trigger(no NW+uB), uB DS, RF trig
4140 140MeV 58Ni, coincidence trigger(no NW+uB), uB DS, RF trig
4141 140MeV 58Ni, coincidence trigger(no NW+uB), uB DS, RF trig
4142 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4143 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4144 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4145 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4146 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4147 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4148 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4149 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4150 140MeV 124Sn, coincidence trigger(no NW+uB), uB DS, RF trig
4151 140MeV Ramp, DS In, blank, MB=3, 10K
4152 140MeV Ramp, DS In, blank, MB=1, 10K
4153 140MeV Ramp, DS In, , MB=1, no beam
4154 140MeV Ramp, DS In, 112Sn, MB=1, 10k
4155 140MeV Ramp, DS In, 112Sn, MB=1, 100k
4156 140MeV Ramp, DS In, 112Sn, MB=3, 10k
4157 140MeV Ramp, DS In, -, MB=3, no beam
4158 140MeV Ramp, DS In, 58Ni, MB=3, 10K
4159 140MeV Ramp, DS In, 58Ni, MB=1, 10K
4160 140MeV Ramp, DS In, -, MB=1, no beam
4161 140MeV Ramp, DS In, 64Ni, MB=1, 10K
4162 140MeV Ramp, DS In, 64Ni, MB=1, 10K
4163 140MeV Ramp, DS In, 64Ni, MB=1, 0.1M
4164 140MeV Ramp, DS In, 64Ni, MB=3, 0.1M
4165 140MeV Ramp, DS In, 64Ni, MB=3, 10K
4166 140MeV Ramp, DS In, 64Ni, MB=3, 10K
4167 140MeV Ramp, DS In, -, MB=3, no beam
4168 140MeV Ramp, DS In, 124Sn, MB=3, 10K
4169 140MeV Ramp, DS In, 124Sn, MB=3, 0.1M
4170 140MeV Ramp, DS In, 124Sn, MB=3, 0.1M
4171 140MeV Ramp, DS In, 124Sn, MB=1, 0.1M
4172 140MeV Ramp, DS In, 124Sn, MB=1, 10K
4173 140MeV Ramp, -, 124Sn, MB=1, no beam
4174 140MeV Ramp, 124Sn, MB=1, 10K
4175 140MeV Ramp, 124Sn, MB=1, no beam
4176 140MeV Ramp, 64Ni, MB=1, 10K
4177 140MeV Ramp, 64Ni, MB=1, no beam
4178 140MeV Ramp, 58Ni, MB=1, 10K
4179 140MeV Ramp, 58Ni, MB=1, no beam
4180 140MeV Ramp, 112Sn, MB=1, 10K
4181 140MeV Ramp, 112Sn, MB=1, no beam
4182 140MeV Ramp, Blank, MB=1, 10K
4183 140MeV 48Ca, Sn124, uBall+Hira, uBall DS
4184 vetowall co64 source
4185 vetowall co64 source bottom
4186 vetowall co64 source top
4188 vetowall  pedestal
4189 140MeV, Blank, Coin with uB and HiRA
4190 140MeV, 124Sn, Coin with uB and HiRA
4191 140MeV, 124Sn, Coin with uB and HiRA
4192 140MeV, 124Sn, Coin with uB and HiRA
4193 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4194 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4195 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4196 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4197 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4198 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4199 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4200 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4201 Ca48 at 140MeV, NW+uB coinc, uB DS, Sn124
4202 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, Blank
4203 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 112Sn
4204 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 112Sn
4205 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 112Sn
4206 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 112Sn
4207 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 112Sn
4208 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 112Sn
4209 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 112Sn
4210 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, blank
4212 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4213 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4214 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4215 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4216 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4217 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4218 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4219 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 58Ni
4220 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, Blank
4221 Ca48 at 140MeV, NW+uB and HiRA+uB coinc, uB DS, 64Ni
4222 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4223 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4224 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4225 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4226 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4227 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4228 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4229 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4230 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4231 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4232 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4233 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4234 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4235 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4236 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4237 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4238 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4239 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4240 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4241 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4242 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4243 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4244 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4245 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4246 Ca48 at 140MeV, NW+uB, uB DS, blank
4247 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4248 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4249 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4250 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4251 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4252 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4253 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4254 Ca48 at 140MeV, NW+uB, uB DS, Blank
4255 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4256 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4257 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4258 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4259 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4260 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4261 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4262 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4263 Ca48 at 140MeV, NW+uB, uB DS, 58Ni, live time measure beam 200 pa
4264 Ca48 at 140MeV, NW+uB, uB DS, 58Ni, live time measure beam 200 pa
4265 Ca48 at 140MeV, NW+uB, uB DS, blank
4266 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4267 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4268 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4269 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4270 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4271 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4272 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4273 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4274 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4275 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4276 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4277 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4278 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4279 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4280 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4281 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4282 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4283 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4284 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4285 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4286 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4287 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4288 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4289 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4290 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4291 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4292 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4293 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4294 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4295 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4296 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4297 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4298 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4299 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4300 Ca48 at 140MeV, NW+uB, uB DS, 124Sn
4301 Ca48 at 140MeV, NW+uB, uB DS, blank
4302 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4303 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4304 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4305 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4306 Ca48 at 140MeV, NW+uB, uB DS, 112Sn
4307 Ca48 at 140MeV, NW+uB, uB DS, blank
4308 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4309 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4310 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4311 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4312 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4313 Ca48 at 140MeV, NW+uB, uB DS, 58Ni
4314 Ca48 at 140MeV, NW+uB, uB DS, Blank
4315 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4316 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4317 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4318 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4319 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4320 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4321 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4322 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4323 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4324 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4325 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4326 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4327 Ca48 at 140MeV, NW+uB, uB DS, 64Ni
4328 Alphas with SnPb foil in place
4329 Pedestal Run for NW,VW all voltages on
4330 Pedestal Run for NW,VW  only NW ch.40 -2100
4331 Pedestal Run for NW,VW  only NW ch.0 -2210
4332 Ca48 at 56MeV, Coin. Trigger MB and HiRA Singles, CH2
4333 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4334 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4335 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4336 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4337 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4338 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4339 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4340 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4341 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4342 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4343 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4344 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4345 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4346 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4347 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4348 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4349 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4350 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4351 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4352 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4353 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4354 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4355 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4356 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4357 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4358 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4359 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4360 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4361 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4362 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4363 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4364 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4365 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4366 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4367 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4368 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4369 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4370 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4371 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4372 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4373 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4374 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4375 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4376 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4377 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4378 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4379 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4380 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 124Sn
4381 Ca48 at 56MeV, Coin. Trigger Both, MB Singles blank
4382 Ca48 at 56MeV, Coin. Trigger Both, MB Singles blank
4383 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4384 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4385 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4386 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4387 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4388 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4389 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4390 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4391 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4392 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4393 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4394 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4395 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4396 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4397 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4398 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4399 Ca48 at 56MeV, Coin. Trigger Both, MB Singles Ni64
4400 Ca48 at 56MeV, Coin. Trigger Both, MB Singles blank
4401 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4402 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4403 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4404 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4405 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4406 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4407 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4408 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4409 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4410 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4411 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4412 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4413 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4414 Ca48 at 56MeV, Coin. Trigger Both, MB Singles 64Ni
4415 Ca48 at 56MeV, ramp blank mult 3 att 30k
4416 Ca48 at 56MeV, ramp blank mult 1 att 30k
4417 Ca48 at 56MeV, ramp blank mult 1 no beam
4418 Ca48 at 56MeV, ramp 112Sn mult 1 30k
4419 Ca48 at 56MeV, ramp 112Sn mult 3 30k
4420 Ca48 at 56MeV, ramp 112Sn mult 3 30k no beam
4421 Ca48 at 56MeV, ramp 112Sn mult 3 30k
4422 Ca48 at 56MeV, ramp 112Sn mult 3 30k
4423 Ca48 at 56MeV, ramp 112Sn 30k mult 3 no beam
4424 Ca48 at 56MeV, ramp 112Sn 30k mult 1
4425 Ca48 at 56MeV, ramp 112Sn 30k no beam
4426 Ca48 at 56MeV, ramp 58Ni mult 3 30k
4427 Ca48 at 56MeV, ramp 58Ni mult 1 30k
4428 Ca48 at 56MeV, ramp 58Ni mult 1 30k no beam
4429 Ca48 at 56MeV, ramp 64Ni mult 1 30k
4430 Ca48 at 56MeV, ramp 64Ni mult 3 30k
4431 Ca48 at 56MeV, ramp 64Ni mult 3 no beam
4432 Ca48 at 56MeV, ramp 124Sn mult 3 30k
4433 Ca48 at 56MeV, ramp 124Sn mult 1 30k
4434 Ca48 at 56MeV, ramp - mult 1 no beam
4435 Ca48 at 56MeV, ramp 112Sn mult 1 30k
4436 Ca48 at 56MeV, ramp 112Sn mult 3 30k
4437 Ca48 at 56MeV, ramp 112Sn mult 3 no beam
4438 Ca48 at 56MeV, ramp 58Ni mult 3 30k
4439 Ca48 at 56MeV, ramp 58Ni mult 1 30k
4440 Ca48 at 56MeV, ramp notarget noB mult 1
4441 Ca48 at 56MeV, ramp 64Ni mult 1 30k
4442 Ca48 at 56MeV, ramp 64Ni mult 3 30k
4443 Ca48 at 56MeV, ramp blank mult 3 30k
4444 Ca48 at 56MeV, ramp blank mult 1 30k
4445 Ca48 at 56MeV, ramp blank mult 1 30k no scint
4446 Ca48 at 56MeV, blank target, coinc triggers, MB DS 301, mult 3
4447 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4448 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4449 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4450 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4451 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4452 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4453 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4454 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4455 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4456 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4457 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4458 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4459 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4460 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4461 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4462 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4463 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4464 Ca48 at 56MeV, 112Sn target, coinc triggers, MB DS 301, mult 3
4465 Ca48 at 56MeV, blank, coinc triggers, MB DS 301, mult 3
4466 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4467 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4468 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4469 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4470 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4471 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4472 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4473 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4474 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4475 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4476 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4477 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4478 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4479 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4480 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4481 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4482 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4483 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4484 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4485 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4486 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4487 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4488 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4489 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4490 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4491 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4492 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4493 Ca48 at 56MeV, Ni64, coinc triggers, MB DS 301, mult 3
4494 Ca48 at 56MeV, Blank, coinc triggers, MB DS 301, mult 3
4495 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4496 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4497 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4498 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4499 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4500 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4501 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4502 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4503 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4504 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4505 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4506 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4507 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4508 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4509 Ca48 at 56MeV, Ni58, coinc triggers, MB DS 301, mult 3
4510 Ca48 at 56MeV, blank, NW+uB coinc, MB DS 301, mult 3
4511 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4512 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4513 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4514 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4515 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4516 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4517 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4518 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4519 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4520 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4521 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4522 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4523 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4524 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4525 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4526 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4527 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4528 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4529 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4530 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4531 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4532 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4533 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4534 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4535 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4536 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4537 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4538 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4539 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4540 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4541 Ca48 at 56MeV, 124Sn, NW+uB coinc, MB DS 301, mult 3
4542 Ca48 at 56MeV, blank, NW+uB coinc, MB DS 301, mult 3
4543 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4544 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4545 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4546 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4547 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4548 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4549 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4550 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4551 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4552 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4553 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4554 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4555 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4556 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4557 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4558 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4559 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4560 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4561 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4562 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4563 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4564 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4565 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4566 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4567 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4568 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4569 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4570 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4571 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4572 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4573 Ca48 at 56MeV, 64Ni, NW+uB coinc, MB DS 301, mult 3
4574 Ca48 at 56MeV, Blank, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3
4575 No Beam, Blank, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3
4576 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4577 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4578 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4579 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4580 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4581 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4582 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4583 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4584 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 29MeV
4585 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 56MeV
4586 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 56MeV
4587 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 56MeV
4588 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 56MeV
4589 48Ca, CH2, NW+uB coinc, Hira+uB coinc, MB/HiRa DS 301/1 mult 3, 56MeV
4590 48Ca, Blank Rotated, 56MeV
4591 48Ca, Blank , 56MeV, coinc trig, MB singles 301 DS
4592 48Ca, Blank , 56MeV, coinc trig, MB singles 301 DS
4593 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4594 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4595 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4596 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4597 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4598 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4599 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4600 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4601 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4602 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4603 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4604 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4605 48Ca, 112 Sn , 56MeV, coinc trig, MB singles 301 DS
4606 48Ca, blank , 56MeV, coinc trig, MB singles 301 DS
4607 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4608 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4609 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4610 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4611 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4612 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4613 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4614 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4615 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4616 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4617 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4618 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4619 48Ca, 58Ni , 56MeV, coinc trig, MB singles 301 DS
4620 48Ca, Blank , 56MeV, coinc trig, MB singles 301 DS
4621 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4622 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4623 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4624 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4625 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4626 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4627 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4628 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4629 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4630 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4631 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4632 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4633 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4634 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4635 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4636 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4637 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4638 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4639 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4640 48Ca, 124Sn , 56MeV, coinc trig, MB singles 301 DS
4641 48Ca, blank , 56MeV, coinc trig, MB singles 301 DS
4642 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4643 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4644 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4645 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4646 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4647 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4648 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4649 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4650 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4651 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4652 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4653 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4654 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4655 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4656 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4657 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4658 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4659 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4660 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4661 48Ca, 64Ni , 56MeV, coinc trig, MB singles 301 DS
4662 48Ca, blank , 56MeV, coinc trig, MB singles 301 DS
4663 no beam, coinc trig, MB singles 301 DS
4664 VW C060 B18 Bottom(20 cm)
4665 VW C060 B14 Bottom(20 cm)
4666 VW C060 B16 Bottom(20 cm)
4667 VW C060 B01 Bottom(20 cm)
4668 VW C060 B18 Top(20 cm)
4669 VW C060 B14 Top(20 cm)
4670 VW C060 B16 Top(20 cm)
4671 VW C060 B01 Top(20 cm)
4672 VW C060 B05 Bottom(20 cm)
4673 VW C060 B06 Bottom(20 cm)
4674 VW C060 B02 Bottom(20 cm)
4675 VW C060 B09 Bottom(20 cm)
4676 VW C060 B13 Bottom(20 cm)
4677 VW C060 B15 Bottom(20 cm)
4678 VW C060 B03 Bottom(20 cm)
4679 VW C060 B07 Bottom(20 cm)
4680 VW C060 B05 top(20 cm)
4681 VW C060 B06 top(20 cm)
4682 VW C060 B02 top(20 cm)
4683 VW C060 B09 top(20 cm)
4684 VW C060 B13 top(20 cm)
4685 VW C060 B15 top(20 cm)
4686 VW C060 B03 top(20 cm)
4687 VW C060 B07 top(20 cm)
4688 VW C060 B11 top(20 cm)
4689 VW C060 B23 top(20 cm)
4690 VW C060 B19 top(20 cm)
4691 VW C060 B21 top(20 cm)
4692 VW C060 B22 top(20 cm)
4693 VW C060 B24 top(20 cm)
4694 VW C060 B08 top(20 cm)
4695 VW C060 B12 top(20 cm)
4696 VW C060 B20 top(20 cm)
4697 VW C060 B17 top(20 cm)
4698 VW C060 B04 top(20 cm)
4699 VW C060 B10 top(20 cm)
4700 VW C060 P02 top(20 cm)
4701 VW C060 B11 bottom(20 cm)
4702 VW C060 B23 bottom(20 cm)
4703 VW C060 B19 bottom(20 cm)
4704 VW C060 B21 bottom(20 cm)
4705 VW C060 B22 bottom(20 cm)
4706 VW C060 B24 bottom(20 cm)
4707 VW C060 B08 bottom(20 cm)
4708 VW C060 B12 bottom(20 cm)
4709 VW C060 B20 bottom(20 cm)
4710 VW C060 B17 bottom(20 cm)
4711 VW C060 B04 bottom(20 cm)
4712 VW C060 B10 bottom(20 cm)
4713 VW C060 P02 bottom(20 cm)
4714 VW C060 B18 Center
4715 VW C060 B14 Center
4716 VW C060 B16 Center
4717 VW C060 B01 Center
4718 VW C060 B05 Center
4719 VW Co60 B06 Center
4720 VW Co60 B02 Center
4721 VW Co60 B09 Center
4722 VW Co60 B13 Center
4723 VW Co60 B15 Center
4724 VW Co60 B03 Center
4725 VW Co60 B07 Center
4726 VW Co60 B11 Center
4727 VW Co60 B23 Center
4728 VW Co60 B19 Center
4729 VW Co60 B21 Center
4730 VW Co60 B22 Center
4731 VW Co60 B24 Center
4732 VW Co60 B08 Center
4733 VW Co60 B12 Center
4734 VW Co60 B20 Center
4735 VW Co60 B17 Center
4736 VW Co60 B04 Center
4737 VW Co60 B10 Center
4738 VW Co60 P02 Center
4739 VW Co60 B01 Top (20 cm) threshold top-5,bot-1
4740 VW Co60 B01 20cm from top threshold top-2,bot-1
4741 VW Co60 B01 50cm from top threshold top-2,bot-1
4742 VW Co60 B01 80cm from top threshold top-2,bot-1
4743 VW Co60 B01 center threshold top-2,bot-1
4744 VW Co60 B01 80 cm from bottom top-2,bot-1
4745 VW Co60 B01 50 cm from bottom top-2,bot-1
4746 VW Co60 B01 20 cm from bottom top-2,bot-1
4747 VW Co60 B19 50 cm from top 
4748 VW Co60 B20 center 
4749 VW Co60 B20 20cm from top 
4750 VW Co60 B20 60cm from top 
4751 VW Co60 B20 60cm from bottom 
4752 VW Co60 B20 20cm from bottom 
4753 VW Co60 B17 60cm from top 
4754 VW Co60 B17 60cm from bottom 
4755 VW Co60 B08 60cm from bottom 
4756 VW Co60 B08 60cm from top
4757 VW Co60 P02 center
4758 VW Co60 P02 20 cm from top
4759 VW Co60 P02 20 cm from bottom
4760 VW cosmic runs
4761 Si Alpha Run, Post Experiment
4762 Si Pulser Ramp, Course, 0.49-4.99V, 31 steps, 5 seconds, MB1 2,4,6,8,10,12
4763 Si Pulser Ramp, Course, 0.49-4.99V, 31 steps, 5 seconds, MB2 2,4,6,8,10,12
4764 Si Pulser Ramp, Course, 0.49-4.99V, 31 steps, 5 seconds, MB1 1,3,5,7,9,11
4765 Si Pulser Ramp, Course, 0.49-4.99V, 31 steps, 5 seconds, MB2 1,3,5,7,9,11
4766 Si Pulser Ramp, Fine, 0.001-0.091V, 11 steps, 5 seconds, MB2 1,3,5,7,9,11
4767 Si Pulser Ramp, Fine, 0.001-0.091V, 11 steps, 5 seconds, MB1 1,3,5,7,9,11
4768 Si Pulser Ramp, Fine, 0.001-0.091V, 11 steps, 5 seconds, MB1 2,4,6,8,10,12
4769 Si Pulser Ramp, Fine, 0.001-0.091V, 11 steps, 5 seconds, MB2 2,4,6,8,10,12
4770 Si Pulser Ramp, Fine, 0.1-0.532V, 25 steps, 5 seconds, MB2 2,4,6,8,10,12
4771 Si Pulser Ramp, Fine, 0.1-0.532V, 25 steps, 5 seconds, MB1 2,4,6,8,10,12
4772 Si Pulser Ramp, Fine, 0.1-0.532V, 25 steps, 5 seconds, MB1 1,3,5,7,9,11
4773 Si Pulser Ramp, Fine, 0.1-0.532V, 25 steps, 5 seconds, MB1 1,3,5,7,9,11
4774 Si Pulser Ramp, Fine, 0.1-0.532V, 25 steps, 5 seconds, MB2 1,3,5,7,9,11
4775 CsI Tower 1 Shaper 1 Course, 31 steps, 0.002-5V, 101 steps 5 sec, 130 gain
4776 CsI Tower 1 Shaper 1 Course, 31 steps, 0.002-5V, 101 steps 5 sec, 170 gain
4777 CsI Tower 1 Shaper 1 Course, 31 steps, 0.002-5V, 101 steps 5 sec, 200 gain
4778 CsI Tower 1 Shaper 1 Course, 31 steps, 0.001-0.01V, 11 step 5 sec, 200 gain
4779 CsI Tower 1 Shaper 1 Course, 31 steps, 0.001-0.1V, 11 step 5 sec, 170 gain
4780 CsI Tower 1 Shaper 1 Course, 31 steps, 0.001-0.1V, 11 step 5 sec, 130 gain
4781 CsI Tower 2 Shaper 2  0.002-5V, 101 step 5 sec, 130 gain
4782 CsI Tower 2 Shaper 2  0.002-5V, 101 step 5 sec, 170 gain
4783 CsI Tower 2 Shaper 2  0.002-5V, 101 step 5 sec, 170 gain
4784 CsI Tower 2 Shaper 2  0.002-5V, 101 step 5 sec, 200 gain
4785 CsI Tower 2 Shaper 2  0.002-5V, 101 step 5 sec, 200 gain
4786 CsI Tower 2 Shaper 2  0.001-0.1V, 11 step 5 sec, 200 gain
4787 CsI Tower 2 Shaper 2  0.001-0.1V, 11 step 5 sec, 170 gain
4788 CsI Tower 2 Shaper 2  0.001-0.1V, 11 step 5 sec, 130 gain
4789 CsI Tower 3 Shaper 3  0.002-5V, 101 step 5 sec, 130 gain
4790 CsI Tower 3 Shaper 3  0.002-5V, 101 step 5 sec, 130 gain
4791 CsI Tower 3 Shaper 3  0.002-5V, 101 step 5 sec, 130 gain
4792 CsI Tower 3 Shaper 3  0.002-5V, 101 step 5 sec, 170 gain
4793 CsI Tower 3 Shaper 3  0.002-5V, 101 step 5 sec, 200 gain
4794 CsI Tower 3 Shaper 3  0.002-5V, 101 step 5 sec, 200 gain
4795 CsI Tower 3 Shaper 3  0.001-0.1V, 11 step 5 sec, 200 gain
4796 CsI Tower 3 Shaper 3  0.001-0.1V, 11 step 5 sec, 170 gain
4797 CsI Tower 3 Shaper 3  0.001-0.1V, 11 step 5 sec, 130 gain
4798 AmBe Source before NWB; Co60 HV, threshold: 1MeV; VW on
4799 AmBe Source before NWB; 25MeV HV, threshold: 1MeV; VW on
4800 AmBe Source before NWB; Co60 HV, threshold: 1MeV; VW on; bypass Fast Amp
4801 AmBe Source before NWB; 25MeV HV, threshold: 1MeV; VW on; bypass Fast Amp
4802 AmBe ;Co60 HV, threshold: 1MeV; unpluy splitter 1,2,3's CGQDC&IGQDC outputs
4803 NW cosmic ray: 25MeV HV, threshold: 1MeV; VW on
4804 NW cosmic ray: 25MeV HV, threshold: 1MeV; VW on
4805 NW cosmic ray: 25MeV HV, threshold: 1MeV; VW on
4806 NW cosmic ray: 25MeV HV, threshold: 1MeV; VW on
4807 NW cosmic ray: 15MeV HV, threshold: 1MeV; VW on
4808 NW cosmic ray: Half Voltage of (15MeV+25MeV) HV, threshold: 1MeV; VW on
4809 NW cosmic ray: Half Voltage of (15MeV+25MeV) HV, threshold: 1MeV; VW on
4810 NW cosmic ray: 15MeV HV, threshold: 1MeV; VW on
4811 VW B19 Co60 source 50cm from bottom
4812 VW B19 Co60 source 80cm from bottom
4813 VW B20 Co60 source 50cm from bottom
4814 VW B20 Co60 source 80cm from bottom
4815 VW B17 Co60 source 50cm from bottom
4816 VW B17 Co60 source 50cm from bottom
4817 VW B17 Co60 source 50cm from bottom
4818 VW B17 Co60 source 80cm from bottom
4819 VW B4 Co60 source 50cm from bottom
4820 VW B4 Co60 source 80cm from bottom
4821 VW B10 Co60 source 50cm from bottom
4822 VW B10 Co60 source 80cm from bottom
4823 VW P02 Co60 source 50cm from bottom
4824 VW P02 Co60 source 80cm from bottom
4825 VW B22 Co60 source 50cm from bottom
4826 VW B22 Co60 source 80cm from bottom
4827 VW B24 Co60 source 50cm from bottom
4828 VW B24 Co60 source 80cm from bottom
4829 VW B08 Co60 source 50cm from bottom
4830 VW B08 Co60 source 80cm from bottom
4831 VW B12 Co60 source 60cm from bottom
4832 VW B23 Co60 source 60cm from bottom
4833 VW B20 Co60 source 50cm from bottom
4834 VW B20 Co60 source 80cm from bottom
4835 VW B19 Co60 source 50cm from bottom
4836 VW B19 Co60 source 80cm from bottom
4837 VW B13 Co60 source 50cm from bottom
4838 VW B13 Co60 source 80cm from bottom
4839 VW B15 Co60 source 60cm from bottom
4840 VW B9 Co60 source 60cm from bottom
4841 VW B2 Co60 source 60cm from bottom
4842 VW B6 Co60 source 60cm from bottom
4843 VW B5 Co60 source 60cm from bottom
4844 VW B1 Co60 source 60cm from bottom
4845 VW B16 Co60 source 60cm from bottom
4846 VW B14 Co60 source 60cm from bottom
4847 VW B18 Co60 source 60cm from bottom
4848 VW B17 Co60 source 50cm from top
4849 VW B17 Co60 source 90cm from top
4850 VW B04 Co60 source 50cm from top
4851 VW B04 Co60 source 90cm from top
4852 VW B10 Co60 source 50cm from top
4853 VW B10 Co60 source 90cm from top
4854 VW P02 Co60 source 50cm from top
4855 VW P02 Co60 source 90cm from top
4856 VW P22 Co60 source 50cm from top
4857 VW B22 Co60 source 90cm from top
4858 VW B24 Co60 source 50cm from top
4859 VW B24 Co60 source 90cm from top
4860 VW B08 Co60 source 50cm from top
4861 VW B08 Co60 source 90cm from top
4862 VW B12 Co60 source 50cm from top
4863 VW B12 Co60 source 90cm from top
4864 VW B20 Co60 source 50cm from top
4865 VW B20 Co60 source 50cm from top Bottom th 1
4866 VW B20 Co60 source 50cm from top Bottom th 1 all other discs off
4867 VW B20 Co60 source 90cm from top Bottom th 1 all other discs off
4868 VW B23 Co60 source 50cm from top 
4869 VW B23 Co60 source 90cm from top 
4870 VW B19 Co60 source 50cm from top 
4871 VW B19 Co60 source 90cm from top 
4872 VW B13 Co60 source 50cm from top 
4873 VW B13 Co60 source 90cm from top 
4874 VW B15 Co60 source 60cm from top 
4875 VW B09 Co60 source 60cm from top 
4876 VW B02 Co60 source 60cm from top 
4877 VW B06 Co60 source 60cm from top 
4878 VW B05 Co60 source 60cm from top 
4879 VW B01 Co60 source 60cm from top 
4880 VW B01 Co60 source 60cm from top Th1
4881 VW B01 Co60 source 30cm from top Th1
4882 VW B01 Co60 source 80cm from top Th1
4883 VW B01 Co60 source 100cm from top Th1
4884 VW B03 Co60 source 60cm from top
4885 VW B07 Co60 source 60cm from top
4886 VW B11 Co60 source 60cm from top
4887 VW B21 Co60 source 60cm from top
4888 VW B16 Co60 source 60cm from top
4889 VW B14 Co60 source 60cm from top
4890 VW B18 Co60 source 60cm from top
4891 VW B03 Co60 source 60cm from bottom
4892 VW B07 Co60 source 60cm from bottom
4893 VW B11 Co60 source 60cm from bottom
4894 VW B21 Co60 source 60cm from bottom
4895 VW B17 Co60 source 10cm from top
4896 VW B17 Co60 source 30cm from top
4897 VW B17 Co60 source 40cm from top
4898 VW B17 Co60 source 70cm from top
4899 VW B17 Co60 source 80cm from top
4900 VW B17 Co60 source 100cm from top
4901 VW B17 Co60 source 110cm from top
4902 VW B17 Co60 source 110cm from bottom
4903 VW B17 Co60 source 100cm from bottom
4904 VW B17 Co60 source 90cm from bottom
4905 VW B17 Co60 source 70cm from bottom
4906 VW B17 Co60 source 40cm from bottom
4907 VW B17 Co60 source 30cm from bottom
4908 VW B17 Co60 source 10cm from bottom
4909 VW B20 Co60 source 10cm from bottom
4910 VW B20 Co60 source 30cm from bottom
4911 VW B20 Co60 source 40cm from bottom
4912 VW B20 Co60 source 70cm from bottom
4913 VW B20 Co60 source 90cm from bottom
4914 VW B20 Co60 source 100cm from bottom
4915 VW B20 Co60 source 110cm from bottom
4916 VW B20 Co60 source 110cm from top
4917 VW B20 Co60 source 100cm from top
4918 VW B20 Co60 source 80cm from top
4919 VW B20 Co60 source 70cm from top
4920 VW B20 Co60 source 40cm from top
4921 VW B20 Co60 source 30cm from top
4922 VW B20 Co60 source 10cm from top
4923 VW B20 Co60 source 10cm from top
4924 VW B20 Co60 source 10cm from bottom
4925 VW pedestal
4926 NW cosmic ray: Co60 HV, threshold: 1MeV; VW on
4927 NW cosmic ray: 15MeV HV, threshold: 1MeV; VW on
